[flags]
process_memory_as_value = true

[processes]
columns = ["PID", "Name", "CPU%", "GPU%", "Mem%", "GMem%", "R/s", "W/s", "User", "State", "Time"]

[[row]]
  [[row.child]]
    ratio = 2
    type="cpu"
  [[row.child]]
    ratio = 1
    type="mem"
[[row]]
  [[row.child]]
    [[row.child.child]]
      ratio=3
      type="temp"
    [[row.child.child]]
      ratio=2
      type="disk"
  [[row.child]]
    type="net"
[[row]]
  [[row.child]]
    type="proc"
    default=true
